#!/usr/bin/env Rscript

# ============================================================
# Empirical Phase M3: 2010 SPX synthetic rough-Heston recovery
# ------------------------------------------------------------
# Purpose:
#   Synthetic recovery check for the empirical calibration pipeline.
#   The test uses the actual 2010 SPX empirical grid from Phase M1, takes
#   the market-calibrated rough-Heston parameters from Phase M2 as the
#   synthetic truth, generates synthetic option prices by the validated
#   rough-Heston CF/Lewis engine, and then recalibrates rough Heston to
#   those synthetic prices.
#
# This is not an iVi experiment. It tests the inverse problem:
#   if the empirical grid were generated by rough Heston, can the same
#   calibration routine recover the generated IV surface, ATM IV, ATM skew,
#   and short-end skew slope?
#
# Inputs:
#   data/EmpiricalStudy/phaseM_2010_market_panel_output/
#     phaseM2010_market_calibration_panel.csv
#     phaseM2010_expiry_summary.csv
#     phaseM2010_market_atm_skew.csv
#     phaseM2010_empirical_H_for_calibration.csv
#
#   data/EmpiricalStudy/phaseM_2010_rheston_calibration_output/
#     phaseM2010_calibrated_parameters_best.csv
#
# Outputs:
#   data/EmpiricalStudy/phaseM_2010_synthetic_recovery_output/
#     phaseM2010_synthetic_truth_parameters.csv
#     phaseM2010_synthetic_recovery_input_provenance.csv
#     phaseM2010_synthetic_recovery_panel_summary.csv
#     phaseM2010_synthetic_panel.csv
#     phaseM2010_synthetic_recovered_parameters_all_starts.csv
#     phaseM2010_synthetic_recovered_parameters_best.csv
#     phaseM2010_synthetic_parameter_recovery.csv
#     phaseM2010_synthetic_recovery_fit_panel.csv
#     phaseM2010_synthetic_recovery_error_summary.csv
#     phaseM2010_synthetic_recovery_by_expiry.csv
#     phaseM2010_synthetic_recovery_by_region.csv
#     phaseM2010_synthetic_atm_skew_recovery.csv
#     phaseM2010_synthetic_skew_powerlaw_recovery.csv
#     phaseM2010_synthetic_recovery_acceptance_checks.csv
#     phaseM2010_synthetic_recovery_strict_acceptance_checks.csv
#     phaseM2010_synthetic_recovery_final_decision.csv
#     plots as PDF/PNG depending on PHASEM_SYN_PLOT_FORMAT
# ============================================================

suppressPackageStartupMessages({
  library(readr)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
})

# Fixed seed for reproducibility of any stochastic or randomized routines.
set.seed(2712010 + 3)

# ============================================================
# 0. Run controls and paths
# ============================================================

# Environment variables allow the same script to run either as a fast
# diagnostic or as the full synthetic recovery experiment.
SYN_FAST_TEST <- identical(Sys.getenv("PHASEM_SYN_FAST_TEST"), "1")
CLEAN_OUTPUT_DIR <- !identical(Sys.getenv("PHASEM_SYN_CLEAN_OUTPUT", "1"), "0")
SHOW_PLOTS <- FALSE
SAVE_PLOTS <- TRUE
PLOT_FORMAT <- Sys.getenv("PHASEM_SYN_PLOT_FORMAT", "pdf")
OPT_TRACE <- identical(Sys.getenv("PHASEM_SYN_OPT_TRACE", "1"), "1")

# Match the numerical convention used in the empirical calibration run.
DU_TARGET <- if (SYN_FAST_TEST) 0.15 else as.numeric(Sys.getenv("PHASEM_SYN_DU_TARGET", "0.125"))
RICCATI_CORRECTOR_ITERS <- as.integer(Sys.getenv("PHASEM_SYN_RICCATI_CORRECTOR_ITERS", "2"))
LAMBDA_SKEW <- as.numeric(Sys.getenv("PHASEM_SYN_LAMBDA_SKEW", "0"))
if (!is.finite(LAMBDA_SKEW) || abs(LAMBDA_SKEW) > 1e-12) {
  stop("This final synthetic-recovery script is locked to lambda_skew = 0. ",
       "Run with PHASEM_SYN_LAMBDA_SKEW=0 or use a lambda-specific script.")
}

MAX_CALIB_EXPIRIES <- if (SYN_FAST_TEST) 3L else as.integer(Sys.getenv("PHASEM_SYN_MAX_CALIB_EXPIRIES", "8"))
MAX_QUOTES_PER_EXPIRY <- if (SYN_FAST_TEST) 5L else as.integer(Sys.getenv("PHASEM_SYN_MAX_QUOTES_PER_EXPIRY", "15"))
MAXIT_ROUGH_SYN <- if (SYN_FAST_TEST) 60L else as.integer(Sys.getenv("PHASEM_SYN_MAXIT_ROUGH", "180"))
INCLUDE_TRUE_START <- identical(Sys.getenv("PHASEM_SYN_INCLUDE_TRUE_START", "0"), "1")

# Generic thresholds are retained as broad run diagnostics.
# Strict thresholds are used for the final lambda = 0 recovery decision.
# They are intentionally tighter than the generic pass/fail thresholds.
IV_RMSE_PASS_THRESHOLD <- as.numeric(Sys.getenv("PHASEM_SYN_IV_RMSE_PASS", "0.010"))
ATM_SKEW_RMSE_PASS_THRESHOLD <- as.numeric(Sys.getenv("PHASEM_SYN_ATM_SKEW_RMSE_PASS", "0.080"))
PRICE_RMSE_PASS_THRESHOLD <- as.numeric(Sys.getenv("PHASEM_SYN_PRICE_RMSE_PASS", "0.50"))

IV_RMSE_STRICT_THRESHOLD <- as.numeric(Sys.getenv("PHASEM_SYN_IV_RMSE_STRICT", "1e-4"))
ATM_SKEW_RMSE_STRICT_THRESHOLD <- as.numeric(Sys.getenv("PHASEM_SYN_ATM_SKEW_RMSE_STRICT", "1e-3"))
PRICE_RMSE_STRICT_THRESHOLD <- as.numeric(Sys.getenv("PHASEM_SYN_PRICE_RMSE_STRICT", "0.02"))
BETA_DIFF_STRICT_THRESHOLD <- as.numeric(Sys.getenv("PHASEM_SYN_BETA_DIFF_STRICT", "0.005"))
MAX_PARAM_REL_ERROR_STRICT_THRESHOLD <- as.numeric(Sys.getenv("PHASEM_SYN_PARAM_REL_STRICT", "0.02"))

# Lewis-integration truncation is maturity-dependent: shorter maturities
# require a wider integration range to keep the transform inversion stable.
u_max_for_tau_days <- function(td) {
  if (SYN_FAST_TEST) {
    if (td <= 14) return(120)
    if (td <= 45) return(100)
    return(80)
  }
  if (td <= 14) return(180)
  if (td <= 45) return(150)
  if (td <= 100) return(130)
  if (td <= 180) return(120)
  return(110)
}

# The fractional Riccati solver also uses a maturity-dependent time grid.
# The grid is deliberately finer at the short end, where skew diagnostics
# are most sensitive.
n_time_for_tau_days <- function(td) {
  if (SYN_FAST_TEST) {
    if (td <= 14) return(120)
    if (td <= 45) return(100)
    return(80)
  }
  if (td <= 14) return(360)
  if (td <= 45) return(300)
  if (td <= 100) return(260)
  return(220)
}

# Resolve project paths without hard-coding one machine.  The environment
# variable takes precedence; common server/local paths are fallbacks.
base_dir <- Sys.getenv("R_THESIS_BASE")
if (identical(base_dir, "")) {
  if (dir.exists("/work/Home/R_Thesis")) {
    base_dir <- "/work/Home/R_Thesis"
  } else if (dir.exists(path.expand("~/R_Thesis"))) {
    base_dir <- path.expand("~/R_Thesis")
  } else {
    base_dir <- getwd()
  }
}

market_dir <- Sys.getenv(
  "PHASEM_SYN_MARKET_DIR",
  file.path(base_dir, "data", "EmpiricalStudy", "phaseM_2010_market_panel_output")
)
calib_dir <- Sys.getenv(
  "PHASEM_SYN_CALIB_DIR",
  file.path(base_dir, "data", "EmpiricalStudy", "phaseM_2010_rheston_calibration_output")
)
out_dir <- Sys.getenv(
  "PHASEM_SYN_OUT_DIR",
  file.path(base_dir, "data", "EmpiricalStudy", "phaseM_2010_synthetic_recovery_output")
)
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

if (CLEAN_OUTPUT_DIR) {
  old_files <- list.files(out_dir, full.names = TRUE, recursive = FALSE)
  if (length(old_files) > 0L) unlink(old_files, recursive = TRUE, force = TRUE)
}

cat("Input market-panel directory:\n", market_dir, "\n\n", sep = "")
cat("Input calibration directory:\n", calib_dir, "\n\n", sep = "")
cat("Output synthetic-recovery directory:\n", out_dir, "\n\n", sep = "")
cat("SYN_FAST_TEST mode:", SYN_FAST_TEST, "\n")
cat("DU_TARGET:", DU_TARGET, "\n")
cat("MAX_CALIB_EXPIRIES:", MAX_CALIB_EXPIRIES, "\n")
cat("MAX_QUOTES_PER_EXPIRY:", MAX_QUOTES_PER_EXPIRY, "\n")
cat("MAXIT_ROUGH_SYN:", MAXIT_ROUGH_SYN, "\n")
cat("INCLUDE_TRUE_START:", INCLUDE_TRUE_START, "\n\n")

required_market_files <- c(
  "phaseM2010_market_calibration_panel.csv",
  "phaseM2010_expiry_summary.csv",
  "phaseM2010_market_atm_skew.csv",
  "phaseM2010_empirical_H_for_calibration.csv"
)
missing_market_files <- required_market_files[!file.exists(file.path(market_dir, required_market_files))]
if (length(missing_market_files) > 0L) {
  stop("Missing required Phase M1 market files:\n",
       paste(missing_market_files, collapse = "\n"),
       "\nRun PhaseM_2010_market_panel.R first.")
}

best_param_path <- file.path(calib_dir, "phaseM2010_calibrated_parameters_best.csv")
if (!file.exists(best_param_path)) {
  stop("Missing Phase M2 best-parameter file:\n", best_param_path,
       "\nRun PhaseM_2010_rheston_calibration.R first.")
}

plot_save <- function(plot_obj, stem, width, height, dpi = 180) {
  if (isTRUE(SHOW_PLOTS)) print(plot_obj)
  if (isTRUE(SAVE_PLOTS)) {
    path <- file.path(out_dir, paste0(stem, ".", PLOT_FORMAT))
    if (PLOT_FORMAT == "png") {
      ggsave(path, plot_obj, width = width, height = height, dpi = dpi)
    } else {
      ggsave(path, plot_obj, width = width, height = height)
    }
  }
}

safe_rmse <- function(x) {
  x <- x[is.finite(x)]
  if (length(x) == 0L) return(NA_real_)
  sqrt(mean(x^2))
}

safe_mae <- function(x) {
  x <- x[is.finite(x)]
  if (length(x) == 0L) return(NA_real_)
  mean(abs(x))
}

safe_max <- function(x) {
  x <- x[is.finite(x)]
  if (length(x) == 0L) return(NA_real_)
  max(x)
}

parse_day_list <- function(x) {
  if (length(x) == 0L || is.na(x) || !nzchar(x)) return(integer(0))
  as.integer(trimws(unlist(strsplit(as.character(x), ","))))
}

# Metadata helpers recover optional provenance fields when they are present
# in the input files without making them mandatory for the recovery run.
first_finite_numeric_column <- function(df, candidates) {
  for (nm in candidates) {
    if (nm %in% names(df)) {
      vals <- suppressWarnings(as.numeric(df[[nm]]))
      vals <- vals[is.finite(vals)]
      if (length(vals) > 0L) return(vals[1])
    }
  }
  NA_real_
}

first_nonempty_character_column <- function(df, candidates) {
  for (nm in candidates) {
    if (nm %in% names(df)) {
      vals <- as.character(df[[nm]])
      vals <- vals[!is.na(vals) & nzchar(vals)]
      if (length(vals) > 0L) return(vals[1])
    }
  }
  NA_character_
}

# Fail early if an upstream Phase M output is missing a required column.
require_columns <- function(df, required, object_name) {
  missing <- setdiff(required, names(df))
  if (length(missing) > 0L) {
    stop(object_name, " is missing required columns: ", paste(missing, collapse = ", "))
  }
}

# ============================================================
# 1. Black--Scholes functions in forward form
# ============================================================

# Black--Scholes pricing is written in forward form: deterministic carry is
# absorbed into F, while D discounts the payoff back to time zero.
black_call_forward <- function(F, K, tau, sigma, D = 1) {
  if (!is.finite(sigma) || sigma <= 0 || tau <= 0) {
    return(D * max(F - K, 0))
  }
  vol_sqrt <- sigma * sqrt(tau)
  d1 <- (log(F / K) + 0.5 * sigma^2 * tau) / vol_sqrt
  d2 <- d1 - vol_sqrt
  D * (F * pnorm(d1) - K * pnorm(d2))
}

black_vega_forward <- function(F, K, tau, sigma, D = 1) {
  if (!is.finite(sigma) || sigma <= 0 || tau <= 0) return(0)
  vol_sqrt <- sigma * sqrt(tau)
  d1 <- (log(F / K) + 0.5 * sigma^2 * tau) / vol_sqrt
  D * F * dnorm(d1) * sqrt(tau)
}

# B&S implied volatility is recovered from call-equivalent prices using the
# same forward/discount convention as the empirical market panel.
implied_vol_black_call <- function(price, F, K, tau, D = 1, tol = 1e-8) {
  intrinsic <- D * max(F - K, 0)
  upper <- D * F
  if (!is.finite(price) || !is.finite(F) || !is.finite(K) || !is.finite(tau) || !is.finite(D)) return(NA_real_)
  if (tau <= 0 || F <= 0 || K <= 0 || D <= 0) return(NA_real_)
  if (price < intrinsic - 1e-8 || price > upper + 1e-8) return(NA_real_)
  price <- min(max(price, intrinsic + 1e-12), upper - 1e-12)
  f <- function(sig) black_call_forward(F, K, tau, sig, D) - price
  lo <- 1e-5
  hi <- 5.0
  flo <- f(lo)
  fhi <- f(hi)
  if (!is.finite(flo) || !is.finite(fhi) || flo * fhi > 0) return(NA_real_)
  uniroot(f, lower = lo, upper = hi, tol = tol)$root
}

# ============================================================
# 2. Rough-Heston CF and Lewis pricing
# ============================================================

black_cf_log_forward <- function(z, tau, sigma) {
  exp(-0.5 * sigma^2 * tau * (z^2 + 1i * z))
}

# Lewis inversion prices a call from the characteristic function evaluated
# on the contour z = u - i/2 and forward log-moneyness k = log(K/F).
lewis_call_from_cf_generic <- function(k, tau, cf_vec, u_grid, F, D) {
  K <- F * exp(k)
  du <- u_grid[2] - u_grid[1]
  w <- rep(du, length(u_grid))
  w[1L] <- 0.5 * du
  w[length(w)] <- 0.5 * du
  vals <- exp(-1i * u_grid * k) * cf_vec / (u_grid^2 + 0.25)
  integral <- sum(w * Re(vals))
  price <- D * (F - sqrt(F * K) / pi * integral)
  Re(price)
}

is_finite_complex <- function(z) {
  is.finite(Re(z)) && is.finite(Im(z))
}

# Precompute Adams--Bashforth--Moulton weights for the fractional Riccati
# equation.  These weights depend only on maturity, time-grid size, and alpha.
make_abm_precomp <- function(T, n_time, alpha) {
  dt <- T / n_time
  n <- n_time
  lag <- 1:n

  b_lag <- (dt^alpha / base::gamma(alpha + 1)) *
    (lag^alpha - (lag - 1)^alpha)

  a_list <- vector("list", n)
  for (k in 1:n) {
    a <- numeric(k)
    a[1] <- (k - 1)^(alpha + 1) - (k - alpha - 1) * k^alpha
    if (k >= 2) {
      for (j in 1:(k - 1)) {
        lag_kj <- k - j
        a[j + 1] <- (lag_kj + 1)^(alpha + 1) -
          2 * lag_kj^(alpha + 1) +
          (lag_kj - 1)^(alpha + 1)
      }
    }
    a_list[[k]] <- (dt^alpha / base::gamma(alpha + 2)) * a
  }

  beta <- 1 - alpha
  if (abs(beta) < 1e-12) {
    weights_beta <- NULL
  } else {
    lag_beta <- n:1
    weights_beta <- ((lag_beta^beta - (lag_beta - 1)^beta) * dt^beta) /
      base::gamma(beta + 1)
  }

  list(
    T = T,
    n_time = n_time,
    alpha = alpha,
    dt = dt,
    b_lag = b_lag,
    a_list = a_list,
    weights_beta = weights_beta
  )
}

# Solve the rough Heston fractional Riccati equation for one complex argument
# and return the corresponding forward log-price characteristic function.
rough_heston_cf_one_abm <- function(a, pre, par, corrector_iters = 2) {
  n <- pre$n_time
  dt <- pre$dt

  gamma_p <- par$gamma
  theta_p <- par$theta
  nu_p <- par$nu
  rho_p <- par$rho
  V0_p <- par$V0
  alpha_p <- par$alpha

  ccoef <- gamma_p * nu_p

  rhs_fun <- function(y) {
    0.5 * (-a^2 - 1i * a) +
      gamma_p * (1i * a * rho_p * nu_p - 1) * y +
      0.5 * ccoef^2 * y^2
  }

  h <- complex(length = n + 1L)
  fvals <- complex(length = n + 1L)
  h[1L] <- 0 + 0i
  fvals[1L] <- rhs_fun(h[1L])

  ok <- TRUE
  fail_step <- NA_integer_

  for (k in 1:n) {
    h_pred <- sum(pre$b_lag[k:1] * fvals[seq_len(k)])
    if (!is_finite_complex(h_pred) || Mod(h_pred) > 1e10) {
      ok <- FALSE
      fail_step <- k
      break
    }

    a_weights <- pre$a_list[[k]]
    base_term <- sum(a_weights * fvals[seq_len(k)])
    h_new <- h_pred

    for (it in seq_len(corrector_iters)) {
      f_new <- rhs_fun(h_new)
      h_new <- base_term +
        (dt^pre$alpha / base::gamma(pre$alpha + 2)) * f_new
      if (!is_finite_complex(h_new) || Mod(h_new) > 1e10) {
        ok <- FALSE
        fail_step <- k
        break
      }
    }
    if (!ok) break

    h[k + 1L] <- h_new
    fvals[k + 1L] <- rhs_fun(h_new)
    if (!is_finite_complex(fvals[k + 1L]) || Mod(fvals[k + 1L]) > 1e12) {
      ok <- FALSE
      fail_step <- k
      break
    }
  }

  if (!ok) {
    return(list(cf = NA_complex_, ok = FALSE, fail_step = fail_step, max_mod_h = safe_max(Mod(h))))
  }

  int_h <- dt * (sum(h) - 0.5 * h[1L] - 0.5 * h[length(h)])
  I_beta_h_T <- if (abs(1 - alpha_p) < 1e-12) {
    h[length(h)]
  } else {
    sum(pre$weights_beta * h[seq_len(n)])
  }

  exponent <- gamma_p * theta_p * int_h + V0_p * I_beta_h_T
  if (!is_finite_complex(exponent) || Re(exponent) > 700) {
    return(list(cf = NA_complex_, ok = FALSE, fail_step = NA_integer_, max_mod_h = safe_max(Mod(h))))
  }

  cf <- exp(exponent)
  list(cf = cf, ok = is_finite_complex(cf), fail_step = NA_integer_, max_mod_h = safe_max(Mod(h)))
}

# Compute the characteristic-function values needed for all strikes sharing
# the same maturity.  Reusing this grid avoids solving the Riccati equation
# separately for every strike.
compute_cf_grid_for_maturity <- function(T, u_grid, par, n_time, corrector_iters = 2) {
  pre <- make_abm_precomp(T = T, n_time = n_time, alpha = par$alpha)
  cf <- complex(length = length(u_grid))
  ok <- logical(length(u_grid))
  max_mod_h <- numeric(length(u_grid))

  for (idx in seq_along(u_grid)) {
    a <- u_grid[idx] - 0.5i
    res <- rough_heston_cf_one_abm(a, pre, par, corrector_iters)
    cf[idx] <- res$cf
    ok[idx] <- isTRUE(res$ok)
    max_mod_h[idx] <- res$max_mod_h
  }

  tibble(
    u = u_grid,
    cf_real = Re(cf),
    cf_imag = Im(cf),
    cf_ok = ok,
    max_mod_h = max_mod_h
  )
}

# Price a panel maturity by maturity.  Each maturity has a common forward,
# discount factor, integration grid, and fractional Riccati time grid.
price_rheston_panel <- function(panel, par, corrector_iters = 2) {
  out_list <- list()
  idx <- 1L
  bad_cf_total <- 0L
  clipped_total <- 0L

  for (td in sort(unique(panel$tau_days))) {
    d <- panel %>% filter(tau_days == td) %>% arrange(k)
    Tval <- unique(d$tau)[1]
    Fval <- unique(d$F)[1]
    Dval <- unique(d$D)[1]

    u_max <- u_max_for_tau_days(td)
    n_u <- ceiling(u_max / DU_TARGET)
    u_grid <- seq(0, u_max, length.out = n_u + 1L)
    n_time <- n_time_for_tau_days(td)

    cf_tbl <- compute_cf_grid_for_maturity(
      T = Tval,
      u_grid = u_grid,
      par = par,
      n_time = n_time,
      corrector_iters = corrector_iters
    )

    bad_cf <- sum(!cf_tbl$cf_ok | !is.finite(cf_tbl$cf_real) | !is.finite(cf_tbl$cf_imag))
    bad_cf_total <- bad_cf_total + bad_cf

    if (bad_cf > 0L) {
      return(list(ok = FALSE, panel = NULL, bad_cf_total = bad_cf_total, clipped_total = clipped_total))
    }

    cf_vec <- cf_tbl$cf_real + 1i * cf_tbl$cf_imag

    rows <- lapply(seq_len(nrow(d)), function(i) {
      kval <- d$k[i]
      Kval <- d$K[i]
      price_raw <- lewis_call_from_cf_generic(
        k = kval,
        tau = Tval,
        cf_vec = cf_vec,
        u_grid = u_grid,
        F = Fval,
        D = Dval
      )
      intrinsic <- Dval * max(Fval - Kval, 0)
      upper <- Dval * Fval
      price <- min(max(price_raw, intrinsic + 1e-10), upper - 1e-10)
      clipped <- abs(price - price_raw) > 1e-7
      iv <- implied_vol_black_call(price, Fval, Kval, Tval, Dval)

      tibble(
        row_id = d$row_id[i],
        model_price_raw = price_raw,
        model_price = price,
        model_iv = iv,
        model_price_clipped = clipped,
        model_n_time = n_time,
        model_u_max = u_max,
        model_n_u = n_u
      )
    })

    out_list[[idx]] <- bind_rows(rows)
    clipped_total <- clipped_total + sum(out_list[[idx]]$model_price_clipped, na.rm = TRUE)
    idx <- idx + 1L
  }

  fit_panel <- panel %>% left_join(bind_rows(out_list), by = "row_id")
  list(ok = TRUE, panel = fit_panel, bad_cf_total = bad_cf_total, clipped_total = clipped_total)
}

# ============================================================
# 3. Read empirical grid, roughness decision, and synthetic truth
# ============================================================

panel_all <- read_csv(file.path(market_dir, "phaseM2010_market_calibration_panel.csv"), show_col_types = FALSE)
expiry_summary <- read_csv(file.path(market_dir, "phaseM2010_expiry_summary.csv"), show_col_types = FALSE)
market_atm <- read_csv(file.path(market_dir, "phaseM2010_market_atm_skew.csv"), show_col_types = FALSE)
empirical_H_input <- read_csv(file.path(market_dir, "phaseM2010_empirical_H_for_calibration.csv"), show_col_types = FALSE)
best_params_all <- read_csv(best_param_path, show_col_types = FALSE)

require_columns(
  panel_all,
  c("tau_days", "tau", "k", "K", "F", "D", "iv_mkt", "call_equiv_price",
    "weight_iv", "calibration_flag", "holdout_flag"),
  "phaseM2010_market_calibration_panel.csv"
)
require_columns(
  empirical_H_input,
  c("selected_for_calibration", "estimator", "n_maturities", "maturity_days_used",
    "beta_hat", "H_hat", "H_for_calibration", "alpha_for_calibration",
    "H_was_clipped", "r_squared", "selection_rule", "calibration_expiries_days",
    "interpretation"),
  "phaseM2010_empirical_H_for_calibration.csv"
)
require_columns(
  best_params_all,
  c("model", "selected_best", "ok_eval", "start_id", "objective", "convergence",
    "gamma", "theta", "nu", "rho", "V0", "alpha", "H"),
  "phaseM2010_calibrated_parameters_best.csv"
)

# The synthetic recovery keeps the same roughness decision used in the
# empirical calibration, so alpha is not re-estimated in this experiment.
H_decision <- empirical_H_input %>%
  filter(selected_for_calibration, is.finite(H_for_calibration), is.finite(alpha_for_calibration)) %>%
  slice(1L) %>%
  transmute(
    H_source = estimator,
    n_maturities,
    maturity_days_used,
    beta_hat,
    H_hat,
    H_for_calibration,
    alpha_for_calibration,
    H_was_clipped,
    r_squared,
    selection_rule,
    calibration_expiries_days,
    interpretation
  )

if (nrow(H_decision) != 1L) {
  stop("No selected empirical H estimate found in phaseM2010_empirical_H_for_calibration.csv")
}

HEADLINE_H_DAYS <- parse_day_list(H_decision$maturity_days_used[1])
H_FIXED <- as.numeric(H_decision$H_for_calibration[1])
ALPHA_FIXED <- as.numeric(H_decision$alpha_for_calibration[1])

# The synthetic data-generating parameter vector is the selected empirical
# rough Heston fit from the lambda = 0 calibration run.
truth_row <- best_params_all %>%
  filter(model == "rough_heston_fixed_alpha", selected_best, ok_eval) %>%
  slice(1L)

if (nrow(truth_row) != 1L) {
  stop("Could not identify a selected, ok_eval rough_heston_fixed_alpha row in phaseM2010_calibrated_parameters_best.csv")
}

truth_par <- list(
  gamma = as.numeric(truth_row$gamma[1]),
  theta = as.numeric(truth_row$theta[1]),
  nu = as.numeric(truth_row$nu[1]),
  rho = as.numeric(truth_row$rho[1]),
  V0 = as.numeric(truth_row$V0[1]),
  alpha = as.numeric(truth_row$alpha[1]),
  H = as.numeric(truth_row$H[1])
)

if (any(!is.finite(unlist(truth_par))) || truth_par$alpha <= 0.5 || truth_par$alpha >= 1) {
  stop("Invalid rough-Heston synthetic-truth parameters read from Phase M2 best-parameter file.")
}

if (abs(truth_par$H - H_FIXED) > 1e-8 || abs(truth_par$alpha - ALPHA_FIXED) > 1e-8) {
  stop("Synthetic-truth roughness does not match the empirical H decision: ",
       "truth H/alpha = ", truth_par$H, "/", truth_par$alpha,
       ", empirical H/alpha = ", H_FIXED, "/", ALPHA_FIXED, ".")
}

truth_tbl <- tibble(
  truth_source = "phaseM2010_calibrated_parameters_best.csv: rough_heston_fixed_alpha selected_best",
  original_start_id = truth_row$start_id[1],
  original_objective = truth_row$objective[1],
  original_convergence = truth_row$convergence[1],
  gamma = truth_par$gamma,
  theta = truth_par$theta,
  nu = truth_par$nu,
  rho = truth_par$rho,
  V0 = truth_par$V0,
  alpha = truth_par$alpha,
  H = truth_par$H,
  H_fixed_from_market_skew = H_FIXED,
  alpha_fixed_from_market_skew = ALPHA_FIXED,
  headline_H_maturities_days = paste(HEADLINE_H_DAYS, collapse = ", ")
)
write_csv(truth_tbl, file.path(out_dir, "phaseM2010_synthetic_truth_parameters.csv"))

cat("Synthetic truth parameters:\n")
print(truth_tbl)

# ============================================================
# 4. Construct the empirical grid used for synthetic recovery
# ============================================================

# Start from the empirical calibration panel but keep the original market
# prices and IVs as provenance; they are replaced by synthetic values below.
panel0 <- panel_all %>%
  mutate(
    row_id = row_number(),
    tau_days = as.integer(tau_days),
    tau = as.numeric(tau),
    k = as.numeric(k),
    K = as.numeric(K),
    F = as.numeric(F),
    D = as.numeric(D),
    iv_market_original = as.numeric(iv_mkt),
    price_market_original = as.numeric(call_equiv_price),
    weight_iv = as.numeric(weight_iv),
    calibration_flag = as.logical(calibration_flag),
    holdout_flag = as.logical(holdout_flag)
  ) %>%
  filter(
    tau_days <= 365,
    abs(k) <= 0.35,
    is.finite(iv_market_original),
    is.finite(weight_iv),
    weight_iv > 0
  )

S0_PROXY <- first_finite_numeric_column(
  panel_all,
  c("S0", "spot", "spot_price", "underlying", "underlying_price", "adj_close", "close", "index_level")
)
VALUATION_DATE <- first_nonempty_character_column(
  panel_all,
  c("obs_date", "date", "valuation_date", "trade_date")
)

input_provenance <- tibble(
  market_panel_file = file.path(market_dir, "phaseM2010_market_calibration_panel.csv"),
  expiry_summary_file = file.path(market_dir, "phaseM2010_expiry_summary.csv"),
  market_atm_skew_file = file.path(market_dir, "phaseM2010_market_atm_skew.csv"),
  empirical_H_file = file.path(market_dir, "phaseM2010_empirical_H_for_calibration.csv"),
  calibrated_parameter_file = best_param_path,
  valuation_date = VALUATION_DATE,
  S0_proxy = S0_PROXY,
  original_market_iv_column = "iv_mkt",
  original_market_price_column = "call_equiv_price",
  synthetic_price_source = "rough-Heston CF/Lewis price generated from the selected market-calibrated rough-Heston parameter vector",
  synthetic_iv_source = "B&S implied volatility inverted from synthetic CF/Lewis call-equivalent prices",
  calibration_iv_column_after_synthetic_replacement = "iv_mkt = synthetic_iv",
  calibration_price_column_after_synthetic_replacement = "call_equiv_price = synthetic_price",
  output_directory = out_dir
)
write_csv(input_provenance, file.path(out_dir, "phaseM2010_synthetic_recovery_input_provenance.csv"))

# Use the same short-end expiry selection logic as the empirical calibration,
# with a hard check that the headline H maturities are retained.
selected_expiries <- panel0 %>%
  filter(calibration_flag) %>%
  distinct(tau_days) %>%
  arrange(tau_days) %>%
  slice_head(n = MAX_CALIB_EXPIRIES) %>%
  pull(tau_days)

if (length(setdiff(HEADLINE_H_DAYS, selected_expiries)) > 0L) {
  stop("Selected calibration expiries do not contain all headline H maturities: missing ",
       paste(setdiff(HEADLINE_H_DAYS, selected_expiries), collapse = ", "),
       ". Increase PHASEM_SYN_MAX_CALIB_EXPIRIES or inspect the market panel.")
}

panel_work <- panel0 %>%
  filter(tau_days %in% selected_expiries) %>%
  group_by(tau_days) %>%
  arrange(abs(k), .by_group = TRUE) %>%
  mutate(rank_near_atm = row_number()) %>%
  ungroup() %>%
  filter(rank_near_atm <= MAX_QUOTES_PER_EXPIRY | holdout_flag) %>%
  mutate(
    calib_used = calibration_flag & rank_near_atm <= MAX_QUOTES_PER_EXPIRY,
    holdout_used = holdout_flag & rank_near_atm <= MAX_QUOTES_PER_EXPIRY
  )

calib_panel_raw <- panel_work %>% filter(calib_used)
holdout_panel_raw <- panel_work %>% filter(holdout_used)
eval_panel_raw <- panel_work %>% filter(calib_used | holdout_used)

if (nrow(calib_panel_raw) < 10L) {
  stop("Too few synthetic calibration quotes after filtering. Inspect market-panel output.")
}
if (nrow(holdout_panel_raw) < 1L) {
  stop("No holdout quotes are available after synthetic-recovery filtering. Inspect holdout_flag and quote selection.")
}

panel_summary <- tibble(
  syn_fast_test = SYN_FAST_TEST,
  lambda_skew = LAMBDA_SKEW,
  valuation_date = VALUATION_DATE,
  S0_proxy = S0_PROXY,
  selected_expiries = paste(selected_expiries, collapse = ", "),
  n_total_market_panel_quotes_after_basic_filter = nrow(panel0),
  n_calibration_quotes = nrow(calib_panel_raw),
  n_holdout_quotes = nrow(holdout_panel_raw),
  max_calib_expiries = MAX_CALIB_EXPIRIES,
  max_quotes_per_expiry = MAX_QUOTES_PER_EXPIRY,
  du_target = DU_TARGET,
  truth_gamma = truth_par$gamma,
  truth_theta = truth_par$theta,
  truth_nu = truth_par$nu,
  truth_rho = truth_par$rho,
  truth_V0 = truth_par$V0,
  truth_alpha = truth_par$alpha,
  truth_H = truth_par$H,
  headline_H_maturities_days = paste(HEADLINE_H_DAYS, collapse = ", "),
  original_market_iv_column = "iv_mkt",
  synthetic_iv_replaces_market_iv_column = TRUE,
  original_market_price_column = "call_equiv_price",
  synthetic_price_replaces_market_price_column = TRUE,
  maxit_rough_synthetic = MAXIT_ROUGH_SYN,
  include_true_start = INCLUDE_TRUE_START
)
write_csv(panel_summary, file.path(out_dir, "phaseM2010_synthetic_recovery_panel_summary.csv"))
print(panel_summary)

# ============================================================
# 5. Generate synthetic prices and B&S implied volatilities
# ============================================================

cat("\nGenerating synthetic rough-Heston prices on empirical grid...\n")
# Generate synthetic prices on the empirical grid before any recalibration.
# This separates the forward-pricing check from the inverse recovery problem.
synthetic_priced <- price_rheston_panel(eval_panel_raw, truth_par, corrector_iters = RICCATI_CORRECTOR_ITERS)
if (!isTRUE(synthetic_priced$ok)) {
  stop("Synthetic price generation failed: bad_cf_total = ", synthetic_priced$bad_cf_total)
}

synthetic_panel <- synthetic_priced$panel %>%
  rename(
    synthetic_price_raw = model_price_raw,
    synthetic_price = model_price,
    synthetic_iv = model_iv,
    synthetic_price_clipped = model_price_clipped,
    synthetic_n_time = model_n_time,
    synthetic_u_max = model_u_max,
    synthetic_n_u = model_n_u
  ) %>%
  mutate(
    synthetic_price_error_vs_market = synthetic_price - price_market_original,
    synthetic_iv_error_vs_market = synthetic_iv - iv_market_original,
    iv_mkt = synthetic_iv,
    call_equiv_price = synthetic_price,
    sample = case_when(
      calib_used ~ "calibration",
      holdout_used ~ "holdout",
      TRUE ~ "other"
    ),
    moneyness_region = case_when(
      abs(k) <= 0.05 ~ "core_abs_k_le_0p05",
      abs(k) <= 0.10 ~ "near_abs_k_le_0p10",
      TRUE ~ "outer_abs_k_gt_0p10"
    )
  ) %>%
  filter(is.finite(synthetic_iv), is.finite(synthetic_price))

write_csv(synthetic_panel, file.path(out_dir, "phaseM2010_synthetic_panel.csv"))

calib_panel <- synthetic_panel %>% filter(calib_used)
holdout_panel <- synthetic_panel %>% filter(holdout_used)
eval_panel <- synthetic_panel %>% filter(calib_used | holdout_used)

# ============================================================
# 6. Calibration parameter transforms and starting values
# ============================================================

# Parameters are optimized on an unconstrained scale and mapped back to
# economically admissible bounds before pricing.
logit <- function(x, lo, hi) log((x - lo) / (hi - x))
inv_logit <- function(y, lo, hi) lo + (hi - lo) / (1 + exp(-y))

bounds <- list(
  gamma = c(0.05, 5.00),
  theta = c(0.005, 0.50),
  nu = c(0.03, 1.50),
  rho = c(-0.95, -0.02),
  V0 = c(0.005, 0.50),
  H = c(0.03, 0.49)
)

clip_to_bounds <- function(x, b, eps = 1e-6) {
  pmin(pmax(x, b[1] + eps), b[2] - eps)
}

make_par <- function(gamma, theta, nu, rho, V0, alpha_fixed = NULL) {
  alpha <- if (is.null(alpha_fixed)) ALPHA_FIXED else alpha_fixed
  list(
    gamma = gamma,
    theta = theta,
    nu = nu,
    rho = rho,
    V0 = V0,
    H = alpha - 0.5,
    alpha = alpha
  )
}

pack_rough <- function(p) {
  c(
    logit(p$gamma, bounds$gamma[1], bounds$gamma[2]),
    logit(p$theta, bounds$theta[1], bounds$theta[2]),
    logit(p$nu, bounds$nu[1], bounds$nu[2]),
    logit(p$rho, bounds$rho[1], bounds$rho[2]),
    logit(p$V0, bounds$V0[1], bounds$V0[2])
  )
}

unpack_rough <- function(x) {
  make_par(
    gamma = inv_logit(x[1], bounds$gamma[1], bounds$gamma[2]),
    theta = inv_logit(x[2], bounds$theta[1], bounds$theta[2]),
    nu = inv_logit(x[3], bounds$nu[1], bounds$nu[2]),
    rho = inv_logit(x[4], bounds$rho[1], bounds$rho[2]),
    V0 = inv_logit(x[5], bounds$V0[1], bounds$V0[2]),
    alpha_fixed = truth_par$alpha
  )
}

perturb_truth <- function(gamma_mult = 1, theta_mult = 1, nu_mult = 1,
                          rho_shift = 0, V0_mult = 1) {
  make_par(
    gamma = clip_to_bounds(truth_par$gamma * gamma_mult, bounds$gamma),
    theta = clip_to_bounds(truth_par$theta * theta_mult, bounds$theta),
    nu = clip_to_bounds(truth_par$nu * nu_mult, bounds$nu),
    rho = clip_to_bounds(truth_par$rho + rho_shift, bounds$rho),
    V0 = clip_to_bounds(truth_par$V0 * V0_mult, bounds$V0),
    alpha_fixed = truth_par$alpha
  )
}

first_atm_iv <- market_atm %>%
  filter(tau_days %in% selected_expiries, is.finite(atm_iv)) %>%
  arrange(tau_days) %>%
  pull(atm_iv)

V0_start <- if (length(first_atm_iv) > 0L) pmin(pmax(first_atm_iv[1]^2, 0.01), 0.20) else 0.045
theta_start <- if (length(first_atm_iv) > 0L) pmin(pmax(tail(first_atm_iv, 1)^2, 0.01), 0.20) else 0.04

# Starting values are perturbations of the synthetic truth and generic
# rough Heston values.  The true start can be added only as a diagnostic.
synthetic_starts <- list(
  perturb_truth(gamma_mult = 0.80, theta_mult = 1.10, nu_mult = 0.90, rho_shift = 0.05, V0_mult = 1.10),
  perturb_truth(gamma_mult = 1.25, theta_mult = 0.85, nu_mult = 1.15, rho_shift = -0.05, V0_mult = 0.85),
  make_par(1.5, 0.040, 0.45, -0.70, 0.045, alpha_fixed = truth_par$alpha),
  make_par(0.8, theta_start, 0.35, -0.65, V0_start, alpha_fixed = truth_par$alpha),
  make_par(2.2, 0.035, 0.60, -0.80, 0.055, alpha_fixed = truth_par$alpha)
)

if (INCLUDE_TRUE_START) {
  synthetic_starts <- c(list(truth_par), synthetic_starts)
}
if (SYN_FAST_TEST) {
  synthetic_starts <- synthetic_starts[seq_len(min(2L, length(synthetic_starts)))]
}

start_design_summary <- tibble(
  start_id = seq_along(synthetic_starts),
  gamma = sapply(synthetic_starts, `[[`, "gamma"),
  theta = sapply(synthetic_starts, `[[`, "theta"),
  nu = sapply(synthetic_starts, `[[`, "nu"),
  rho = sapply(synthetic_starts, `[[`, "rho"),
  V0 = sapply(synthetic_starts, `[[`, "V0"),
  alpha = sapply(synthetic_starts, `[[`, "alpha"),
  H = sapply(synthetic_starts, `[[`, "H"),
  include_true_start = INCLUDE_TRUE_START,
  maxit = MAXIT_ROUGH_SYN
)
write_csv(start_design_summary, file.path(out_dir, "phaseM2010_synthetic_start_design_summary.csv"))
print(start_design_summary)

# ============================================================
# 7. Objective function and synthetic calibration
# ============================================================

# Black--Scholes/Lewis control: the Lewis implementation must reproduce
# known B&S prices before it is used for rough Heston recovery.
run_black_lewis_sanity <- function(panel) {
  maturity_rows <- panel %>%
    distinct(tau_days, tau, F, D) %>%
    arrange(tau_days)

  test_rows <- tidyr::expand_grid(
    maturity_rows,
    k_test = c(-0.10, 0.00, 0.10)
  )

  sigma_test <- 0.22

  details <- lapply(seq_len(nrow(test_rows)), function(i) {
    td <- test_rows$tau_days[i]
    Tval <- test_rows$tau[i]
    Fval <- test_rows$F[i]
    Dval <- test_rows$D[i]
    kval <- test_rows$k_test[i]
    Kval <- Fval * exp(kval)

    u_max <- u_max_for_tau_days(td)
    n_u <- ceiling(u_max / DU_TARGET)
    u_grid <- seq(0, u_max, length.out = n_u + 1L)
    cf_vec <- sapply(u_grid, function(u) black_cf_log_forward(u - 0.5i, Tval, sigma_test))

    p_black <- black_call_forward(Fval, Kval, Tval, sigma_test, Dval)
    p_lewis <- lewis_call_from_cf_generic(kval, Tval, cf_vec, u_grid, Fval, Dval)

    tibble(
      tau_days = td,
      tau = Tval,
      k = kval,
      u_max = u_max,
      n_u = n_u,
      price_black = p_black,
      price_lewis = p_lewis,
      abs_error = abs(p_black - p_lewis)
    )
  }) %>% bind_rows()

  summary <- details %>%
    summarise(
      max_abs_error = max(abs_error, na.rm = TRUE),
      mean_abs_error = mean(abs_error, na.rm = TRUE),
      pass = max_abs_error < 1e-4
    )

  list(details = details, summary = summary)
}

# Local near-ATM slope used only inside the optional skew penalty.  The
# reported ATM-skew estimates are recomputed later with the full estimator.
local_slope_for_objective <- function(x, y, window = 0.055) {
  ok <- is.finite(x) & is.finite(y) & abs(x) <= window
  x <- x[ok]
  y <- y[ok]
  if (length(x) < 4L) return(NA_real_)
  if (sum(x < -0.002) < 1L || sum(x > 0.002) < 1L) return(NA_real_)
  w <- pmax(0, 1 - abs(x) / window)
  fit <- tryCatch(lm(y ~ x, weights = w), error = function(e) NULL)
  if (is.null(fit)) return(NA_real_)
  unname(coef(fit)["x"])
}

objective_from_fit <- function(fit_panel) {
  d <- fit_panel %>%
    filter(calib_used) %>%
    mutate(resid = model_iv - synthetic_iv) %>%
    filter(is.finite(resid), is.finite(weight_iv))

  if (nrow(d) < 0.80 * nrow(calib_panel)) return(1e7)

  iv_loss <- mean(d$weight_iv * d$resid^2)

  if (!is.finite(LAMBDA_SKEW) || LAMBDA_SKEW <= 0) return(iv_loss)

  skew_tbl <- d %>%
    group_by(tau_days) %>%
    summarise(
      synthetic_skew = local_slope_for_objective(k, synthetic_iv),
      model_skew = local_slope_for_objective(k, model_iv),
      .groups = "drop"
    ) %>%
    filter(is.finite(synthetic_skew), is.finite(model_skew)) %>%
    mutate(skew_error = model_skew - synthetic_skew)

  if (nrow(skew_tbl) < 3L) return(1e7)

  skew_loss <- mean(skew_tbl$skew_error^2)
  iv_loss + LAMBDA_SKEW * skew_loss
}

# Recalibrate rough Heston to the synthetic B&S implied-volatility panel.
# Successful recovery supports the calibration pipeline on this fixed grid.
calibrate_rough_synthetic <- function(starts) {
  cat("\nCalibrating rough Heston to synthetic prices with", length(starts), "starts...\n")
  results <- vector("list", length(starts))

  for (sidx in seq_along(starts)) {
    cat("  start", sidx, "of", length(starts), "\n")
    x0 <- pack_rough(starts[[sidx]])

    obj <- function(x) {
      par <- unpack_rough(x)
      priced <- price_rheston_panel(calib_panel, par, corrector_iters = RICCATI_CORRECTOR_ITERS)
      if (!isTRUE(priced$ok)) return(1e8)
      if (priced$clipped_total > 0L) return(1e7 + 1e5 * priced$clipped_total)
      val <- objective_from_fit(priced$panel)
      if (!is.finite(val)) return(1e8)
      val
    }

    fit <- optim(
      par = x0,
      fn = obj,
      method = "Nelder-Mead",
      control = list(
        maxit = MAXIT_ROUGH_SYN,
        reltol = 1e-5,
        trace = ifelse(OPT_TRACE, 1, 0),
        REPORT = 20
      )
    )

    par_hat <- unpack_rough(fit$par)
    priced_eval <- price_rheston_panel(eval_panel, par_hat, corrector_iters = RICCATI_CORRECTOR_ITERS)

    results[[sidx]] <- list(
      fit = fit,
      par = par_hat,
      priced_eval = priced_eval,
      ok = isTRUE(priced_eval$ok)
    )
  }

  obj_values <- sapply(results, function(x) x$fit$value)
  best_idx <- which.min(obj_values)
  list(
    model_name = "rough_heston_fixed_alpha_synthetic_recovery",
    results = results,
    best_idx = best_idx,
    best = results[[best_idx]]
  )
}

black_sanity <- run_black_lewis_sanity(calib_panel)
write_csv(black_sanity$details, file.path(out_dir, "phaseM2010_synthetic_black_lewis_sanity_details.csv"))
write_csv(black_sanity$summary, file.path(out_dir, "phaseM2010_synthetic_black_lewis_sanity.csv"))
print(black_sanity$summary)
if (!isTRUE(black_sanity$summary$pass[1])) {
  stop("Black--Scholes/Lewis control failed. Do not run synthetic recovery until the pricing convention is fixed.")
}

syn_cal <- calibrate_rough_synthetic(synthetic_starts)

extract_synthetic_param_tbl <- function(cal) {
  rows <- lapply(seq_along(cal$results), function(i) {
    p <- cal$results[[i]]$par
    tibble(
      model = cal$model_name,
      start_id = i,
      selected_best = i == cal$best_idx,
      objective = cal$results[[i]]$fit$value,
      convergence = cal$results[[i]]$fit$convergence,
      gamma = p$gamma,
      theta = p$theta,
      nu = p$nu,
      rho = p$rho,
      V0 = p$V0,
      alpha = p$alpha,
      H = p$H,
      ok_eval = cal$results[[i]]$ok,
      eval_bad_cf_total = ifelse(isTRUE(cal$results[[i]]$ok), cal$results[[i]]$priced_eval$bad_cf_total, NA_integer_),
      eval_clipped_total = ifelse(isTRUE(cal$results[[i]]$ok), cal$results[[i]]$priced_eval$clipped_total, NA_integer_)
    )
  })
  bind_rows(rows)
}

param_tbl <- extract_synthetic_param_tbl(syn_cal)
write_csv(param_tbl, file.path(out_dir, "phaseM2010_synthetic_recovered_parameters_all_starts.csv"))
print(param_tbl)

objective_gap_summary <- param_tbl %>%
  filter(is.finite(objective)) %>%
  arrange(objective) %>%
  summarise(
    n_starts = nrow(param_tbl),
    n_finite_objectives = n(),
    n_ok_eval = sum(param_tbl$ok_eval, na.rm = TRUE),
    n_convergence_code_0 = sum(param_tbl$convergence == 0, na.rm = TRUE),
    selected_start_id = first(start_id),
    best_objective = first(objective),
    second_best_objective = ifelse(n() >= 2L, objective[2], NA_real_),
    objective_gap_second_minus_best = ifelse(n() >= 2L, objective[2] - objective[1], NA_real_),
    objective_ratio_second_over_best = ifelse(n() >= 2L, objective[2] / objective[1], NA_real_),
    best_convergence_code = first(convergence),
    robustness_comment = case_when(
      !is.finite(second_best_objective) ~ "Only one finite synthetic objective; optimisation robustness is weak.",
      best_convergence_code != 0 ~ "Best synthetic recovery start did not report convergence code 0; inspect before strong claims.",
      objective_ratio_second_over_best <= 1.15 ~ "Several starts are close to the best synthetic objective; local-start sensitivity appears limited.",
      TRUE ~ "Best synthetic objective is isolated; treat recovery as local."
    )
  )
write_csv(objective_gap_summary, file.path(out_dir, "phaseM2010_synthetic_optimization_robustness_summary.csv"))
print(objective_gap_summary)

best_recovered <- param_tbl %>% filter(selected_best)
write_csv(best_recovered, file.path(out_dir, "phaseM2010_synthetic_recovered_parameters_best.csv"))

# ============================================================
# 8. Surface and parameter recovery summaries
# ============================================================

recovered_par <- syn_cal$best$par

# Parameter recovery is reported separately from surface recovery because
# option-price inverse problems can be weakly identified.
parameter_recovery <- tibble(
  parameter = c("gamma", "theta", "nu", "rho", "V0", "alpha", "H"),
  true_value = c(truth_par$gamma, truth_par$theta, truth_par$nu, truth_par$rho, truth_par$V0, truth_par$alpha, truth_par$H),
  recovered_value = c(recovered_par$gamma, recovered_par$theta, recovered_par$nu, recovered_par$rho, recovered_par$V0, recovered_par$alpha, recovered_par$H)
) %>%
  mutate(
    absolute_error = recovered_value - true_value,
    relative_error = ifelse(abs(true_value) > 1e-12, absolute_error / true_value, NA_real_),
    abs_relative_error = abs(relative_error)
  )
write_csv(parameter_recovery, file.path(out_dir, "phaseM2010_synthetic_parameter_recovery.csv"))
print(parameter_recovery)

recovered_panel <- syn_cal$best$priced_eval$panel %>%
  mutate(
    model = "rough Heston recovered from synthetic panel",
    iv_error = model_iv - synthetic_iv,
    price_error = model_price - synthetic_price,
    sample = case_when(
      calib_used ~ "calibration",
      holdout_used ~ "holdout",
      TRUE ~ "other"
    ),
    moneyness_region = case_when(
      abs(k) <= 0.05 ~ "core_abs_k_le_0p05",
      abs(k) <= 0.10 ~ "near_abs_k_le_0p10",
      TRUE ~ "outer_abs_k_gt_0p10"
    )
  )

error_summary <- recovered_panel %>%
  filter(sample %in% c("calibration", "holdout")) %>%
  group_by(sample) %>%
  summarise(
    n_quotes = n(),
    n_price_clipped = sum(model_price_clipped, na.rm = TRUE),
    n_na_iv = sum(!is.finite(model_iv)),
    iv_rmse = safe_rmse(iv_error),
    iv_mae = safe_mae(iv_error),
    price_rmse = safe_rmse(price_error),
    price_mae = safe_mae(price_error),
    max_abs_iv_error = safe_max(abs(iv_error)),
    max_abs_price_error = safe_max(abs(price_error)),
    .groups = "drop"
  ) %>%
  arrange(sample)

error_by_expiry <- recovered_panel %>%
  filter(sample %in% c("calibration", "holdout")) %>%
  group_by(sample, tau_days, tau) %>%
  summarise(
    n_quotes = n(),
    iv_rmse = safe_rmse(iv_error),
    iv_mae = safe_mae(iv_error),
    price_rmse = safe_rmse(price_error),
    max_abs_iv_error = safe_max(abs(iv_error)),
    .groups = "drop"
  ) %>%
  arrange(sample, tau_days)

error_by_region <- recovered_panel %>%
  filter(sample %in% c("calibration", "holdout")) %>%
  group_by(sample, moneyness_region) %>%
  summarise(
    n_quotes = n(),
    iv_rmse = safe_rmse(iv_error),
    iv_mae = safe_mae(iv_error),
    price_rmse = safe_rmse(price_error),
    max_abs_iv_error = safe_max(abs(iv_error)),
    .groups = "drop"
  ) %>%
  arrange(sample, moneyness_region)

write_csv(recovered_panel, file.path(out_dir, "phaseM2010_synthetic_recovery_fit_panel.csv"))
write_csv(error_summary, file.path(out_dir, "phaseM2010_synthetic_recovery_error_summary.csv"))
write_csv(error_by_expiry, file.path(out_dir, "phaseM2010_synthetic_recovery_by_expiry.csv"))
write_csv(error_by_region, file.path(out_dir, "phaseM2010_synthetic_recovery_by_region.csv"))
print(error_summary)

# ============================================================
# 9. ATM-skew and short-end power-law recovery
# ============================================================

# ATM skew is estimated from a near-ATM local polynomial in forward
# log-moneyness, matching the market-panel extraction convention.
estimate_atm_skew <- function(df, iv_col, window = 0.055) {
  d <- df %>%
    filter(abs(k) <= window, is.finite(.data[[iv_col]])) %>%
    arrange(k)

  n_left <- sum(d$k < -1e-10)
  n_right <- sum(d$k > 1e-10)
  two_sided_support <- n_left >= 1L && n_right >= 1L

  if (nrow(d) < 3L || !two_sided_support) {
    return(tibble(
      atm_iv = NA_real_, atm_skew = NA_real_, n_local = nrow(d),
      n_left = n_left, n_right = n_right, two_sided_support = two_sided_support,
      fit_type = "insufficient"
    ))
  }

  d <- d %>% mutate(local_weight = pmax(0, 1 - abs(k) / window))
  fit_type <- ifelse(nrow(d) >= 5L && n_left >= 2L && n_right >= 2L, "local_quadratic", "local_linear")
  form <- if (fit_type == "local_quadratic") {
    as.formula(paste0(iv_col, " ~ k + I(k^2)"))
  } else {
    as.formula(paste0(iv_col, " ~ k"))
  }

  fit <- tryCatch(lm(form, data = d, weights = local_weight), error = function(e) NULL)
  if (is.null(fit)) {
    return(tibble(
      atm_iv = NA_real_, atm_skew = NA_real_, n_local = nrow(d),
      n_left = n_left, n_right = n_right, two_sided_support = two_sided_support,
      fit_type = "failed"
    ))
  }

  cf <- coef(fit)
  tibble(
    atm_iv = unname(cf["(Intercept)"]),
    atm_skew = unname(cf["k"]),
    n_local = nrow(d),
    n_left = n_left,
    n_right = n_right,
    two_sided_support = two_sided_support,
    fit_type = fit_type
  )
}

synthetic_skew_eval <- eval_panel %>%
  group_by(tau_days, tau) %>%
  group_modify(~ estimate_atm_skew(.x, "synthetic_iv", window = 0.055)) %>%
  ungroup() %>%
  mutate(series = "synthetic truth")

recovered_skew_eval <- recovered_panel %>%
  group_by(tau_days, tau) %>%
  group_modify(~ estimate_atm_skew(.x, "model_iv", window = 0.055)) %>%
  ungroup() %>%
  mutate(series = "recovered model")

atm_skew_recovery <- recovered_skew_eval %>%
  select(tau_days, tau,
         recovered_atm_iv = atm_iv,
         recovered_atm_skew = atm_skew,
         recovered_n_local = n_local,
         recovered_n_left = n_left,
         recovered_n_right = n_right,
         recovered_two_sided_support = two_sided_support,
         recovered_fit_type = fit_type) %>%
  left_join(
    synthetic_skew_eval %>%
      select(tau_days, tau,
             synthetic_atm_iv = atm_iv,
             synthetic_atm_skew = atm_skew,
             synthetic_n_local = n_local,
             synthetic_n_left = n_left,
             synthetic_n_right = n_right,
             synthetic_two_sided_support = two_sided_support,
             synthetic_fit_type = fit_type),
    by = c("tau_days", "tau")
  ) %>%
  mutate(
    atm_iv_error = recovered_atm_iv - synthetic_atm_iv,
    atm_skew_error = recovered_atm_skew - synthetic_atm_skew,
    abs_atm_skew_error = abs(atm_skew_error),
    in_headline_H_window = tau_days %in% HEADLINE_H_DAYS
  ) %>%
  arrange(tau_days)

atm_skew_summary <- atm_skew_recovery %>%
  summarise(
    n_expiries = sum(is.finite(atm_skew_error)),
    atm_iv_rmse = safe_rmse(atm_iv_error),
    atm_skew_rmse = safe_rmse(atm_skew_error),
    atm_skew_mae = safe_mae(atm_skew_error),
    max_abs_atm_skew_error = safe_max(abs_atm_skew_error)
  )

atm_skew_summary_headline <- atm_skew_recovery %>%
  filter(in_headline_H_window) %>%
  summarise(
    n_expiries = sum(is.finite(atm_skew_error)),
    headline_H_maturities_days = paste(sort(unique(tau_days[is.finite(atm_skew_error)])), collapse = ", "),
    atm_iv_rmse = safe_rmse(atm_iv_error),
    atm_skew_rmse = safe_rmse(atm_skew_error),
    atm_skew_mae = safe_mae(atm_skew_error),
    max_abs_atm_skew_error = safe_max(abs_atm_skew_error)
  )

# The short-end power-law slope is estimated on the headline maturity set
# used for the empirical H decision.
fit_skew_powerlaw <- function(skew_tbl, skew_col, label, day_filter = HEADLINE_H_DAYS) {
  d <- skew_tbl %>%
    filter(tau_days %in% day_filter, is.finite(.data[[skew_col]]), abs(.data[[skew_col]]) > 0, tau > 0) %>%
    mutate(log_tau = log(tau), log_abs_skew = log(abs(.data[[skew_col]]))) %>%
    arrange(tau_days)

  if (nrow(d) < 3L) {
    return(tibble(
      series = label,
      n_maturities = nrow(d),
      maturity_days_used = paste(d$tau_days, collapse = ", "),
      intercept = NA_real_,
      beta_hat = NA_real_,
      H_hat = NA_real_,
      r_squared = NA_real_
    ))
  }

  fit <- lm(log_abs_skew ~ log_tau, data = d)
  tibble(
    series = label,
    n_maturities = nrow(d),
    maturity_days_used = paste(d$tau_days, collapse = ", "),
    intercept = unname(coef(fit)["(Intercept)"]),
    beta_hat = unname(coef(fit)["log_tau"]),
    H_hat = unname(coef(fit)["log_tau"]) + 0.5,
    r_squared = summary(fit)$r.squared
  )
}

skew_powerlaw_recovery <- bind_rows(
  fit_skew_powerlaw(atm_skew_recovery, "synthetic_atm_skew", "synthetic truth"),
  fit_skew_powerlaw(atm_skew_recovery, "recovered_atm_skew", "recovered model")
) %>%
  mutate(
    true_H_parameter = truth_par$H,
    true_alpha_parameter = truth_par$alpha,
    headline_H_days = paste(HEADLINE_H_DAYS, collapse = ", ")
  )

write_csv(atm_skew_recovery, file.path(out_dir, "phaseM2010_synthetic_atm_skew_recovery.csv"))
write_csv(atm_skew_summary, file.path(out_dir, "phaseM2010_synthetic_atm_skew_recovery_summary.csv"))
write_csv(atm_skew_summary_headline, file.path(out_dir, "phaseM2010_synthetic_atm_skew_recovery_headline_H_summary.csv"))
write_csv(skew_powerlaw_recovery, file.path(out_dir, "phaseM2010_synthetic_skew_powerlaw_recovery.csv"))
print(atm_skew_summary)
print(atm_skew_summary_headline)
print(skew_powerlaw_recovery)

# ============================================================
# 10. Martingale checks and recovery diagnostics
# ============================================================

# Characteristic-function martingale checks verify phi(0)=1 and phi(-i)=1
# for both the synthetic truth and the recovered model.
martingale_checks <- bind_rows(lapply(sort(unique(eval_panel$tau_days)), function(td) {
  Tval <- unique(eval_panel$tau[eval_panel$tau_days == td])[1]
  nt <- n_time_for_tau_days(td)

  check_one <- function(par, label) {
    pre <- make_abm_precomp(T = Tval, n_time = nt, alpha = par$alpha)
    cf0 <- rough_heston_cf_one_abm(0 + 0i, pre, par, RICCATI_CORRECTOR_ITERS)
    cf_m1 <- rough_heston_cf_one_abm(-1i, pre, par, RICCATI_CORRECTOR_ITERS)
    tibble(
      model = label,
      tau_days = td,
      tau = Tval,
      n_time = nt,
      abs_phi0_minus_1 = Mod(cf0$cf - 1),
      abs_phim1_minus_1 = Mod(cf_m1$cf - 1),
      phi0_ok = isTRUE(cf0$ok),
      phim1_ok = isTRUE(cf_m1$ok)
    )
  }

  bind_rows(
    check_one(truth_par, "synthetic truth"),
    check_one(recovered_par, "recovered model")
  )
}))
write_csv(martingale_checks, file.path(out_dir, "phaseM2010_synthetic_martingale_checks.csv"))

calibration_row <- error_summary %>% filter(sample == "calibration")
holdout_row <- error_summary %>% filter(sample == "holdout")
headline_skew_rmse <- atm_skew_summary_headline$atm_skew_rmse[1]
all_skew_rmse <- atm_skew_summary$atm_skew_rmse[1]

acceptance <- tibble(
  check = c(
    "Black--Scholes/Lewis control passed",
    "synthetic price generation completed",
    "synthetic rough-Heston recovery calibration completed",
    "best synthetic recovery convergence code equals 0",
    "no synthetic-generation price clipping",
    "no recovered-model price clipping on eval panel",
    "calibration IV RMSE below threshold",
    "holdout IV RMSE below threshold",
    "calibration price RMSE below threshold",
    "holdout price RMSE below threshold",
    "headline ATM-skew RMSE below threshold",
    "truth/recovered max |phi(0)-1| < 1e-6",
    "truth/recovered max |phi(-i)-1| < 1e-6"
  ),
  value = c(
    as.numeric(isTRUE(black_sanity$summary$pass[1])),
    as.numeric(isTRUE(synthetic_priced$ok)),
    as.numeric(isTRUE(syn_cal$best$priced_eval$ok)),
    syn_cal$best$fit$convergence,
    sum(synthetic_panel$synthetic_price_clipped, na.rm = TRUE),
    sum(recovered_panel$model_price_clipped, na.rm = TRUE),
    calibration_row$iv_rmse[1],
    holdout_row$iv_rmse[1],
    calibration_row$price_rmse[1],
    holdout_row$price_rmse[1],
    headline_skew_rmse,
    safe_max(martingale_checks$abs_phi0_minus_1),
    safe_max(martingale_checks$abs_phim1_minus_1)
  ),
  pass = c(
    isTRUE(black_sanity$summary$pass[1]),
    isTRUE(synthetic_priced$ok),
    isTRUE(syn_cal$best$priced_eval$ok),
    syn_cal$best$fit$convergence == 0,
    sum(synthetic_panel$synthetic_price_clipped, na.rm = TRUE) == 0,
    sum(recovered_panel$model_price_clipped, na.rm = TRUE) == 0,
    calibration_row$iv_rmse[1] < IV_RMSE_PASS_THRESHOLD,
    holdout_row$iv_rmse[1] < IV_RMSE_PASS_THRESHOLD,
    calibration_row$price_rmse[1] < PRICE_RMSE_PASS_THRESHOLD,
    holdout_row$price_rmse[1] < PRICE_RMSE_PASS_THRESHOLD,
    headline_skew_rmse < ATM_SKEW_RMSE_PASS_THRESHOLD,
    safe_max(martingale_checks$abs_phi0_minus_1) < 1e-6,
    safe_max(martingale_checks$abs_phim1_minus_1) < 1e-6
  )
)
write_csv(acceptance, file.path(out_dir, "phaseM2010_synthetic_recovery_acceptance_checks.csv"))
print(acceptance)

# Strict decision diagnostics for the final lambda = 0 recovery check.
# These checks are more restrictive than the generic diagnostics above and
# determine whether the run is strong enough to report as the main
# synthetic recovery sensitivity result.
beta_synthetic <- skew_powerlaw_recovery %>%
  filter(series == "synthetic truth") %>%
  pull(beta_hat)
beta_recovered <- skew_powerlaw_recovery %>%
  filter(series == "recovered model") %>%
  pull(beta_hat)
beta_abs_diff <- ifelse(
  length(beta_synthetic) == 1L && length(beta_recovered) == 1L &&
    is.finite(beta_synthetic) && is.finite(beta_recovered),
  abs(beta_recovered - beta_synthetic),
  NA_real_
)

max_param_abs_rel_error <- parameter_recovery %>%
  filter(!(parameter %in% c("alpha", "H")), is.finite(abs_relative_error)) %>%
  summarise(value = max(abs_relative_error, na.rm = TRUE)) %>%
  pull(value)
if (!is.finite(max_param_abs_rel_error)) max_param_abs_rel_error <- NA_real_

strict_acceptance <- tibble(
  check = c(
    "best synthetic recovery convergence code equals 0",
    "calibration IV RMSE < strict threshold",
    "holdout IV RMSE < strict threshold",
    "calibration price RMSE < strict threshold",
    "holdout price RMSE < strict threshold",
    "headline ATM-skew RMSE < strict threshold",
    "absolute beta-slope recovery error < strict threshold",
    "max nonfixed-parameter relative error < strict threshold",
    "no synthetic-generation price clipping",
    "no recovered-model price clipping on eval panel",
    "truth/recovered max |phi(0)-1| < 1e-6",
    "truth/recovered max |phi(-i)-1| < 1e-6"
  ),
  value = c(
    syn_cal$best$fit$convergence,
    calibration_row$iv_rmse[1],
    holdout_row$iv_rmse[1],
    calibration_row$price_rmse[1],
    holdout_row$price_rmse[1],
    headline_skew_rmse,
    beta_abs_diff,
    max_param_abs_rel_error,
    sum(synthetic_panel$synthetic_price_clipped, na.rm = TRUE),
    sum(recovered_panel$model_price_clipped, na.rm = TRUE),
    safe_max(martingale_checks$abs_phi0_minus_1),
    safe_max(martingale_checks$abs_phim1_minus_1)
  ),
  threshold = c(
    0,
    IV_RMSE_STRICT_THRESHOLD,
    IV_RMSE_STRICT_THRESHOLD,
    PRICE_RMSE_STRICT_THRESHOLD,
    PRICE_RMSE_STRICT_THRESHOLD,
    ATM_SKEW_RMSE_STRICT_THRESHOLD,
    BETA_DIFF_STRICT_THRESHOLD,
    MAX_PARAM_REL_ERROR_STRICT_THRESHOLD,
    0,
    0,
    1e-6,
    1e-6
  ),
  pass = c(
    syn_cal$best$fit$convergence == 0,
    calibration_row$iv_rmse[1] < IV_RMSE_STRICT_THRESHOLD,
    holdout_row$iv_rmse[1] < IV_RMSE_STRICT_THRESHOLD,
    calibration_row$price_rmse[1] < PRICE_RMSE_STRICT_THRESHOLD,
    holdout_row$price_rmse[1] < PRICE_RMSE_STRICT_THRESHOLD,
    headline_skew_rmse < ATM_SKEW_RMSE_STRICT_THRESHOLD,
    is.finite(beta_abs_diff) && beta_abs_diff < BETA_DIFF_STRICT_THRESHOLD,
    is.finite(max_param_abs_rel_error) && max_param_abs_rel_error < MAX_PARAM_REL_ERROR_STRICT_THRESHOLD,
    sum(synthetic_panel$synthetic_price_clipped, na.rm = TRUE) == 0,
    sum(recovered_panel$model_price_clipped, na.rm = TRUE) == 0,
    safe_max(martingale_checks$abs_phi0_minus_1) < 1e-6,
    safe_max(martingale_checks$abs_phim1_minus_1) < 1e-6
  )
)

final_decision <- tibble(
  lambda_skew = LAMBDA_SKEW,
  valuation_date = VALUATION_DATE,
  S0_proxy = S0_PROXY,
  selected_expiries = paste(selected_expiries, collapse = ", "),
  headline_H_maturities_days = paste(HEADLINE_H_DAYS, collapse = ", "),
  n_calibration_quotes = nrow(calib_panel),
  n_holdout_quotes = nrow(holdout_panel),
  calibration_iv_rmse = calibration_row$iv_rmse[1],
  holdout_iv_rmse = holdout_row$iv_rmse[1],
  calibration_price_rmse = calibration_row$price_rmse[1],
  holdout_price_rmse = holdout_row$price_rmse[1],
  headline_atm_skew_rmse = headline_skew_rmse,
  synthetic_beta_hat = beta_synthetic[1],
  recovered_beta_hat = beta_recovered[1],
  beta_abs_diff = beta_abs_diff,
  max_nonfixed_param_abs_relative_error = max_param_abs_rel_error,
  all_generic_acceptance_checks_pass = all(acceptance$pass),
  all_strict_acceptance_checks_pass = all(strict_acceptance$pass),
  thesis_grade_recovery_decision = ifelse(
    all(strict_acceptance$pass),
    "PASS: strong synthetic surface, parameter, and ATM-skew recovery on the empirical grid.",
    "REVIEW: generic recovery completed, but at least one strict thesis-grade diagnostic failed."
  )
)

write_csv(strict_acceptance, file.path(out_dir, "phaseM2010_synthetic_recovery_strict_acceptance_checks.csv"))
write_csv(final_decision, file.path(out_dir, "phaseM2010_synthetic_recovery_final_decision.csv"))
cat("\nStrict thesis-grade acceptance checks:\n")
print(strict_acceptance)
cat("\nFinal synthetic recovery decision:\n")
print(final_decision)

# ============================================================
# 11. Plots
# ============================================================

# Plot formatting is kept consistent with the other Phase M figures.
plot_theme <- theme_minimal(base_size = 11) +
  theme(
    plot.title = element_text(face = "bold", size = 12),
    plot.subtitle = element_blank(),
    axis.text = element_text(size = 8.5),
    strip.text = element_text(face = "bold", size = 9),
    legend.position = "bottom",
    panel.grid.minor = element_blank()
  )

series_colours <- c(
  "Synthetic truth" = "#1B9E77",
  "Recovered rough Heston" = "#D95F02"
)
series_linetypes <- c(
  "Synthetic truth" = "solid",
  "Recovered rough Heston" = "dashed"
)
sample_colours <- c(
  "calibration" = "#7570B3",
  "holdout" = "#E7298A"
)

fixed_range <- function(x, pad_frac = 0.04, include_zero = FALSE, symmetric = FALSE) {
  x <- x[is.finite(x)]
  if (length(x) == 0L) return(NULL)
  if (symmetric) {
    m <- max(abs(x), na.rm = TRUE)
    if (!is.finite(m) || m == 0) m <- 1e-6
    return(c(-1, 1) * m * (1 + pad_frac))
  }
  lo <- min(x, na.rm = TRUE)
  hi <- max(x, na.rm = TRUE)
  if (isTRUE(include_zero)) lo <- min(lo, 0)
  if (!is.finite(lo) || !is.finite(hi)) return(NULL)
  if (abs(hi - lo) < 1e-12) {
    pad <- max(abs(hi), 1e-6) * pad_frac
  } else {
    pad <- (hi - lo) * pad_frac
  }
  c(lo - pad, hi + pad)
}

plot_days <- selected_expiries

fit_plot_long <- recovered_panel %>%
  filter(tau_days %in% plot_days, sample %in% c("calibration", "holdout")) %>%
  mutate(tau_label = factor(paste0(tau_days, "d"), levels = paste0(plot_days, "d")))

fit_iv_long <- fit_plot_long %>%
  select(row_id, tau_days, tau_label, k, sample, synthetic_iv, model_iv) %>%
  pivot_longer(
    cols = c(synthetic_iv, model_iv),
    names_to = "series",
    values_to = "iv"
  ) %>%
  mutate(
    series = recode(
      series,
      synthetic_iv = "Synthetic truth",
      model_iv = "Recovered rough Heston"
    ),
    series = factor(series, levels = names(series_colours))
  ) %>%
  arrange(tau_days, series, k)

k_abs_lim <- max(abs(fit_iv_long$k[is.finite(fit_iv_long$k)]), na.rm = TRUE)
if (!is.finite(k_abs_lim) || k_abs_lim <= 0) k_abs_lim <- 0.06
k_lim <- c(-1, 1) * min(max(k_abs_lim * 1.05, 0.06), 0.35)
iv_lim <- fixed_range(fit_iv_long$iv, pad_frac = 0.035, include_zero = FALSE)

p_fit <- fit_iv_long %>%
  ggplot(aes(x = k, y = iv, colour = series, linetype = series, group = series)) +
  geom_line(linewidth = 0.62) +
  geom_point(aes(shape = sample), size = 0.95, alpha = 0.72) +
  facet_wrap(~ tau_label, scales = "fixed") +
  coord_cartesian(xlim = k_lim, ylim = iv_lim) +
  scale_colour_manual(values = series_colours) +
  scale_linetype_manual(values = series_linetypes) +
  labs(
    title = "Synthetic recovery: B&S implied-volatility slices",
    x = expression("Forward log-moneyness " * k == log(K/F[tau])),
    y = "B&S implied volatility",
    colour = "Series",
    linetype = "Series",
    shape = "Sample"
  ) +
  plot_theme
plot_save(p_fit, "plot_phaseM2010_synthetic_iv_recovery", width = 10.5, height = 6.2)

resid_plot_long <- fit_plot_long %>% arrange(tau_days, sample, k)
resid_lim <- fixed_range(resid_plot_long$iv_error, pad_frac = 0.08, symmetric = TRUE)

p_resid <- resid_plot_long %>%
  ggplot(aes(x = k, y = iv_error, colour = sample, group = sample)) +
  geom_hline(yintercept = 0, linewidth = 0.3, colour = "grey30") +
  geom_line(linewidth = 0.48) +
  geom_point(aes(shape = sample), size = 1.05) +
  facet_wrap(~ tau_label, scales = "fixed") +
  coord_cartesian(xlim = k_lim, ylim = resid_lim) +
  scale_colour_manual(values = sample_colours) +
  labs(
    title = "Synthetic recovery: implied-volatility residuals",
    x = expression("Forward log-moneyness " * k == log(K/F[tau])),
    y = "Recovered B&S IV - synthetic B&S IV",
    colour = "Sample",
    shape = "Sample"
  ) +
  plot_theme
plot_save(p_resid, "plot_phaseM2010_synthetic_iv_recovery_residuals", width = 10.5, height = 6.2)

skew_plot <- bind_rows(
  atm_skew_recovery %>%
    select(tau_days, tau, atm_skew = synthetic_atm_skew) %>%
    mutate(series = "Synthetic truth"),
  atm_skew_recovery %>%
    select(tau_days, tau, atm_skew = recovered_atm_skew) %>%
    mutate(series = "Recovered rough Heston")
) %>%
  filter(is.finite(atm_skew), tau_days %in% selected_expiries) %>%
  mutate(series = factor(series, levels = names(series_colours))) %>%
  arrange(series, tau_days)

skew_y_lim <- fixed_range(abs(skew_plot$atm_skew), pad_frac = 0.05, include_zero = TRUE)

p_skew <- skew_plot %>%
  ggplot(aes(x = tau_days, y = abs(atm_skew), colour = series, linetype = series, shape = series, group = series)) +
  geom_line(linewidth = 0.70) +
  geom_point(size = 2.0) +
  coord_cartesian(ylim = skew_y_lim) +
  scale_x_continuous(breaks = selected_expiries) +
  scale_colour_manual(values = series_colours) +
  scale_linetype_manual(values = series_linetypes) +
  labs(
    title = "Synthetic recovery: ATM-skew term structure",
    x = "Time to maturity in days",
    y = "Absolute ATM skew, |d sigma_BS(0,tau) / dk|",
    colour = "Series",
    linetype = "Series",
    shape = "Series"
  ) +
  plot_theme
plot_save(p_skew, "plot_phaseM2010_synthetic_atm_skew_recovery", width = 8.5, height = 5.1)

param_lim <- fixed_range(parameter_recovery$absolute_error, pad_frac = 0.08, symmetric = TRUE)

p_param <- parameter_recovery %>%
  mutate(parameter = factor(parameter, levels = parameter)) %>%
  ggplot(aes(x = parameter, y = absolute_error)) +
  geom_hline(yintercept = 0, linewidth = 0.3, colour = "grey30") +
  geom_col(width = 0.7, fill = "#4D4D4D") +
  coord_cartesian(ylim = param_lim) +
  labs(
    title = "Synthetic recovery: parameter errors",
    x = "Parameter",
    y = "Recovered value - true value"
  ) +
  plot_theme
plot_save(p_param, "plot_phaseM2010_synthetic_parameter_recovery_errors", width = 7.8, height = 4.5)

# ============================================================
# 12. Console summary
# ============================================================

cat("\n============================================================\n")
cat("Synthetic recovery finished.\n")
cat("Output directory:\n", out_dir, "\n", sep = "")
cat("\nBest recovered rough-Heston parameters:\n")
print(best_recovered)
cat("\nParameter recovery:\n")
print(parameter_recovery)
cat("\nError summary:\n")
print(error_summary)
cat("\nATM-skew recovery summary, all selected expiries:\n")
print(atm_skew_summary)
cat("\nATM-skew recovery summary, headline H maturities:\n")
print(atm_skew_summary_headline)
cat("\nShort-end skew power-law recovery:\n")
print(skew_powerlaw_recovery)
cat("\nAcceptance checks:\n")
print(acceptance)
cat("\nStrict thesis-grade acceptance checks:\n")
print(strict_acceptance)
cat("\nFinal synthetic recovery decision:\n")
print(final_decision)
cat("============================================================\n")
